/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const AssistantKnowledgeEntry = IDL.Record({
  'id' : IDL.Text,
  'question' : IDL.Text,
  'isBusinessOps' : IDL.Bool,
  'usageCount' : IDL.Nat,
  'lastUpdated' : IDL.Int,
  'answer' : IDL.Text,
  'isActive' : IDL.Bool,
  'category' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const AdminPageSection = IDL.Variant({
  'b2b' : IDL.Null,
  'marketplace' : IDL.Null,
  'startups' : IDL.Null,
  'assistants' : IDL.Null,
  'businessDetails' : IDL.Null,
  'affiliate' : IDL.Null,
  'funding' : IDL.Null,
});
export const AdminPageStatusDetails = IDL.Record({
  'version' : IDL.Text,
  'notes' : IDL.Text,
});
export const AdminPageSectionStatus = IDL.Record({
  'status' : IDL.Variant({
    'completed' : IDL.Null,
    'comingSoon' : IDL.Null,
    'inProgress' : IDL.Null,
  }),
  'section' : AdminPageSection,
  'details' : IDL.Opt(AdminPageStatusDetails),
});
export const MarketplaceRoadmap = IDL.Record({
  'progressPercentage' : IDL.Nat,
  'name' : IDL.Text,
  'completed' : IDL.Bool,
  'lastUpdated' : IDL.Int,
  'roadmapId' : IDL.Text,
  'notes' : IDL.Text,
});
export const AdminDashboardData = IDL.Record({
  'adminSections' : IDL.Vec(AdminPageSectionStatus),
  'marketplaceRoadmap' : IDL.Vec(MarketplaceRoadmap),
});
export const AccessRole = IDL.Variant({
  'b2bMember' : IDL.Null,
  'startUpMember' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'accountCreated' : IDL.Int,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'subscriptionId' : IDL.Opt(IDL.Text),
  'activeRole' : AccessRole,
});
export const FunnelPartner = IDL.Record({
  'partnerName' : IDL.Text,
  'signupLink' : IDL.Text,
  'profileLink' : IDL.Text,
});
export const PolicyIdentifier = IDL.Variant({
  'terms' : IDL.Null,
  'shipping' : IDL.Null,
  'privacy' : IDL.Null,
  'returns' : IDL.Null,
});
export const PolicySignatureRecord = IDL.Record({
  'signerName' : IDL.Text,
  'signature' : IDL.Text,
  'policyVersion' : IDL.Text,
  'policyIdentifier' : PolicyIdentifier,
  'timestamp' : IDL.Int,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const UnansweredQuestion = IDL.Record({
  'id' : IDL.Text,
  'question' : IDL.Text,
  'creationTime' : IDL.Int,
  'interactionCount' : IDL.Nat,
  'categorySuggestion' : IDL.Text,
});
export const UserRoleSummary = IDL.Record({
  'guestCount' : IDL.Nat,
  'adminCount' : IDL.Nat,
  'userCount' : IDL.Nat,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addKnowledgeEntry' : IDL.Func([AssistantKnowledgeEntry], [], []),
  'askAssistant' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(IDL.Text)],
      ['query'],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'getActiveKnowledgeByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(AssistantKnowledgeEntry)],
      ['query'],
    ),
  'getAdminDashboardData' : IDL.Func([], [AdminDashboardData], ['query']),
  'getAssistantKnowledgeBase' : IDL.Func(
      [],
      [IDL.Vec(AssistantKnowledgeEntry)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFunnelPartner' : IDL.Func([], [FunnelPartner], ['query']),
  'getSignatureByPolicy' : IDL.Func(
      [PolicyIdentifier],
      [IDL.Opt(PolicySignatureRecord)],
      ['query'],
    ),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUnansweredQuestions' : IDL.Func(
      [],
      [IDL.Vec(UnansweredQuestion)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserRoleSummary' : IDL.Func([], [UserRoleSummary], ['query']),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setOwnerPrincipal' : IDL.Func([], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'signPolicy' : IDL.Func([PolicySignatureRecord], [], []),
  'submitBusinessOpsQuestion' : IDL.Func([IDL.Text], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateAdminDashboardData' : IDL.Func([], [], []),
  'updateFunnelPartner' : IDL.Func([FunnelPartner], [], []),
  'updateKnowledgeEntry' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateMarketplaceRoadmap' : IDL.Func([], [], []),
  'verifyPolicySignature' : IDL.Func(
      [PolicyIdentifier, IDL.Text],
      [IDL.Bool],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const AssistantKnowledgeEntry = IDL.Record({
    'id' : IDL.Text,
    'question' : IDL.Text,
    'isBusinessOps' : IDL.Bool,
    'usageCount' : IDL.Nat,
    'lastUpdated' : IDL.Int,
    'answer' : IDL.Text,
    'isActive' : IDL.Bool,
    'category' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const AdminPageSection = IDL.Variant({
    'b2b' : IDL.Null,
    'marketplace' : IDL.Null,
    'startups' : IDL.Null,
    'assistants' : IDL.Null,
    'businessDetails' : IDL.Null,
    'affiliate' : IDL.Null,
    'funding' : IDL.Null,
  });
  const AdminPageStatusDetails = IDL.Record({
    'version' : IDL.Text,
    'notes' : IDL.Text,
  });
  const AdminPageSectionStatus = IDL.Record({
    'status' : IDL.Variant({
      'completed' : IDL.Null,
      'comingSoon' : IDL.Null,
      'inProgress' : IDL.Null,
    }),
    'section' : AdminPageSection,
    'details' : IDL.Opt(AdminPageStatusDetails),
  });
  const MarketplaceRoadmap = IDL.Record({
    'progressPercentage' : IDL.Nat,
    'name' : IDL.Text,
    'completed' : IDL.Bool,
    'lastUpdated' : IDL.Int,
    'roadmapId' : IDL.Text,
    'notes' : IDL.Text,
  });
  const AdminDashboardData = IDL.Record({
    'adminSections' : IDL.Vec(AdminPageSectionStatus),
    'marketplaceRoadmap' : IDL.Vec(MarketplaceRoadmap),
  });
  const AccessRole = IDL.Variant({
    'b2bMember' : IDL.Null,
    'startUpMember' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'accountCreated' : IDL.Int,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'subscriptionId' : IDL.Opt(IDL.Text),
    'activeRole' : AccessRole,
  });
  const FunnelPartner = IDL.Record({
    'partnerName' : IDL.Text,
    'signupLink' : IDL.Text,
    'profileLink' : IDL.Text,
  });
  const PolicyIdentifier = IDL.Variant({
    'terms' : IDL.Null,
    'shipping' : IDL.Null,
    'privacy' : IDL.Null,
    'returns' : IDL.Null,
  });
  const PolicySignatureRecord = IDL.Record({
    'signerName' : IDL.Text,
    'signature' : IDL.Text,
    'policyVersion' : IDL.Text,
    'policyIdentifier' : PolicyIdentifier,
    'timestamp' : IDL.Int,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const UnansweredQuestion = IDL.Record({
    'id' : IDL.Text,
    'question' : IDL.Text,
    'creationTime' : IDL.Int,
    'interactionCount' : IDL.Nat,
    'categorySuggestion' : IDL.Text,
  });
  const UserRoleSummary = IDL.Record({
    'guestCount' : IDL.Nat,
    'adminCount' : IDL.Nat,
    'userCount' : IDL.Nat,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addKnowledgeEntry' : IDL.Func([AssistantKnowledgeEntry], [], []),
    'askAssistant' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'getActiveKnowledgeByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AssistantKnowledgeEntry)],
        ['query'],
      ),
    'getAdminDashboardData' : IDL.Func([], [AdminDashboardData], ['query']),
    'getAssistantKnowledgeBase' : IDL.Func(
        [],
        [IDL.Vec(AssistantKnowledgeEntry)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFunnelPartner' : IDL.Func([], [FunnelPartner], ['query']),
    'getSignatureByPolicy' : IDL.Func(
        [PolicyIdentifier],
        [IDL.Opt(PolicySignatureRecord)],
        ['query'],
      ),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUnansweredQuestions' : IDL.Func(
        [],
        [IDL.Vec(UnansweredQuestion)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserRoleSummary' : IDL.Func([], [UserRoleSummary], ['query']),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setOwnerPrincipal' : IDL.Func([], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'signPolicy' : IDL.Func([PolicySignatureRecord], [], []),
    'submitBusinessOpsQuestion' : IDL.Func([IDL.Text], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateAdminDashboardData' : IDL.Func([], [], []),
    'updateFunnelPartner' : IDL.Func([FunnelPartner], [], []),
    'updateKnowledgeEntry' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateMarketplaceRoadmap' : IDL.Func([], [], []),
    'verifyPolicySignature' : IDL.Func(
        [PolicyIdentifier, IDL.Text],
        [IDL.Bool],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };