/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminCenterAnalytics {
  'pendingPayments' : bigint,
  'averageTransactionAmountCents' : number,
  'failedToSuccessRatio' : number,
  'failedPayments' : bigint,
  'successfulPayments' : bigint,
  'attemptsPerSuccessfulTransaction' : number,
  'totalTransactions' : bigint,
  'totalRevenueCents' : bigint,
}
export interface AdminDashboardData {
  'adminSections' : Array<AdminPageSectionStatus>,
  'marketplaceRoadmap' : Array<MarketplaceRoadmap>,
}
export interface AdminFinancialState {
  'creditAccount' : CreditAccount,
  'availableFundsCents' : bigint,
}
export type AdminPageSection = { 'b2b' : null } |
  { 'marketplace' : null } |
  { 'startups' : null } |
  { 'assistants' : null } |
  { 'businessDetails' : null } |
  { 'affiliate' : null } |
  { 'funding' : null };
export interface AdminPageSectionStatus {
  'status' : { 'completed' : null } |
    { 'comingSoon' : null } |
    { 'inProgress' : null },
  'section' : AdminPageSection,
  'details' : [] | [AdminPageStatusDetails],
}
export interface AdminPageStatusDetails { 'version' : string, 'notes' : string }
export interface AssistantKnowledgeEntry {
  'id' : string,
  'question' : string,
  'isBusinessOps' : boolean,
  'usageCount' : bigint,
  'lastUpdated' : bigint,
  'answer' : string,
  'isActive' : boolean,
  'category' : string,
}
export interface CreditAccount {
  'creditLimitCents' : bigint,
  'usedAmountCents' : bigint,
}
export interface EcomOrder {
  'status' : OrderStatus,
  'sellerPrincipal' : [] | [Principal],
  'shippingCostCents' : bigint,
  'customerPrincipal' : [] | [Principal],
  'orderId' : string,
  'totalAmount' : bigint,
  'products' : Array<string>,
}
export interface MarketplaceRoadmap {
  'progressPercentage' : bigint,
  'name' : string,
  'completed' : boolean,
  'lastUpdated' : bigint,
  'roadmapId' : string,
  'notes' : string,
}
export type OrderStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'inProgress' : null };
export type PayoutTransferStatus = { 'pending' : null } |
  { 'processed' : null } |
  { 'failed' : null };
export interface RoleApplication {
  'status' : RoleApplicationStatus,
  'applicant' : Principal,
  'requestedRole' : UserRole,
  'applicationDate' : bigint,
  'reason' : string,
}
export type RoleApplicationStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface SellerEarningsSummary {
  'totalOrders' : bigint,
  'totalEarnings' : bigint,
  'totalShippingCosts' : bigint,
}
export interface SellerOnboardingProgress {
  'isCompleted' : boolean,
  'lastUpdated' : bigint,
  'timestamps' : Array<[SellerOnboardingStep, bigint]>,
  'currentStep' : SellerOnboardingStep,
  'completedSteps' : Array<SellerOnboardingStep>,
}
export type SellerOnboardingStep = { 'marketing' : null } |
  { 'termsAndConditions' : null } |
  { 'signup' : null } |
  { 'storeSetup' : null } |
  { 'websiteIntegration' : null } |
  { 'companyDetails' : null };
export interface SellerPayoutProfile {
  'sellerPrincipal' : Principal,
  'createdAt' : bigint,
  'lastUpdated' : bigint,
  'designatedPayoutAccount' : string,
  'internalBalanceCents' : bigint,
}
export interface SellerPayoutTransferRecord {
  'id' : string,
  'status' : PayoutTransferStatus,
  'sellerPrincipal' : Principal,
  'createdAt' : bigint,
  'errorMessage' : [] | [string],
  'amountCents' : bigint,
  'processedAt' : [] | [bigint],
  'payoutAccount' : string,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type TimeFrame = { 'today' : null } |
  { 'thisWeek' : null } |
  { 'allTime' : null } |
  { 'thisMonth' : null };
export interface TransactionRecord {
  'id' : string,
  'status' : { 'successful' : null } |
    { 'failed' : null },
  'transactionType' : { 'creditFunding' : null } |
    { 'deposit' : null },
  'source' : string,
  'date' : string,
  'amountCents' : bigint,
  'transactionId' : string,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'accountCreated' : bigint,
  'fullName' : string,
  'email' : string,
  'subscriptionId' : [] | [string],
  'activeRole' : UserRole,
}
export type UserRole = { 'admin' : null } |
  { 'customer' : null } |
  { 'seller' : null } |
  { 'employee' : null } |
  { 'marketer' : null } |
  { 'guest' : null } |
  { 'business' : null };
export interface UserRoleSummary {
  'guestCount' : bigint,
  'adminCount' : bigint,
  'userCount' : bigint,
}
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserWithRole {
  'principal' : Principal,
  'profile' : UserProfile,
  'systemRole' : UserRole__1,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addKnowledgeEntry' : ActorMethod<[AssistantKnowledgeEntry], undefined>,
  'approveRoleApplication' : ActorMethod<[Principal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'assignRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createPayoutTransfer' : ActorMethod<[bigint], string>,
  'deleteKnowledgeEntry' : ActorMethod<[string], undefined>,
  'getAdminCenterAnalytics' : ActorMethod<[], AdminCenterAnalytics>,
  'getAdminDashboardData' : ActorMethod<[], AdminDashboardData>,
  'getAdminFinancialState' : ActorMethod<[], AdminFinancialState>,
  'getAllOrders' : ActorMethod<[], Array<EcomOrder>>,
  'getAllPayoutTransfers' : ActorMethod<[], Array<SellerPayoutTransferRecord>>,
  'getAllSellerPayoutProfiles' : ActorMethod<[], Array<SellerPayoutProfile>>,
  'getAllTransactionHistory' : ActorMethod<[], Array<TransactionRecord>>,
  'getAllUsers' : ActorMethod<[], Array<UserWithRole>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getCustomerOrders' : ActorMethod<[], Array<EcomOrder>>,
  'getKnowledgeBase' : ActorMethod<[], Array<AssistantKnowledgeEntry>>,
  'getOnboarding' : ActorMethod<[], [] | [SellerOnboardingProgress]>,
  'getOwnerEmail' : ActorMethod<[], string>,
  'getPendingRoleApplications' : ActorMethod<[], Array<RoleApplication>>,
  'getSellerEarningsSummary' : ActorMethod<[TimeFrame], SellerEarningsSummary>,
  'getSellerOrders' : ActorMethod<[], Array<EcomOrder>>,
  'getSellerPayoutProfile' : ActorMethod<[], [] | [SellerPayoutProfile]>,
  'getSellerPayoutTransfers' : ActorMethod<
    [],
    Array<SellerPayoutTransferRecord>
  >,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getTransactionRecordById' : ActorMethod<[string], [] | [TransactionRecord]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserRoleSummary' : ActorMethod<[], UserRoleSummary>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerOwnerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'processPayoutTransfer' : ActorMethod<
    [string, boolean, [] | [string]],
    undefined
  >,
  'rejectRoleApplication' : ActorMethod<[Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveOnboarding' : ActorMethod<[SellerOnboardingProgress], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'submitRoleApplication' : ActorMethod<[UserRole, string], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateAdminDashboardData' : ActorMethod<[], undefined>,
  'updateAdminFinancialState' : ActorMethod<[AdminFinancialState], undefined>,
  'updateKnowledgeEntry' : ActorMethod<[AssistantKnowledgeEntry], undefined>,
  'updateSellerPayoutProfile' : ActorMethod<[SellerPayoutProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];