/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const AdminPageSection = IDL.Variant({
  'b2b' : IDL.Null,
  'marketplace' : IDL.Null,
  'startups' : IDL.Null,
  'assistants' : IDL.Null,
  'businessDetails' : IDL.Null,
  'affiliate' : IDL.Null,
  'funding' : IDL.Null,
});
export const AdminPageStatusDetails = IDL.Record({
  'version' : IDL.Text,
  'notes' : IDL.Text,
});
export const AdminPageSectionStatus = IDL.Record({
  'status' : IDL.Variant({
    'completed' : IDL.Null,
    'comingSoon' : IDL.Null,
    'inProgress' : IDL.Null,
  }),
  'section' : AdminPageSection,
  'details' : IDL.Opt(AdminPageStatusDetails),
});
export const MarketplaceRoadmap = IDL.Record({
  'progressPercentage' : IDL.Nat,
  'name' : IDL.Text,
  'completed' : IDL.Bool,
  'lastUpdated' : IDL.Int,
  'roadmapId' : IDL.Text,
  'notes' : IDL.Text,
});
export const AdminDashboardData = IDL.Record({
  'adminSections' : IDL.Vec(AdminPageSectionStatus),
  'marketplaceRoadmap' : IDL.Vec(MarketplaceRoadmap),
});
export const CreditAccount = IDL.Record({
  'creditLimitCents' : IDL.Nat,
  'usedAmountCents' : IDL.Nat,
});
export const AdminFinancialState = IDL.Record({
  'creditAccount' : CreditAccount,
  'availableFundsCents' : IDL.Nat,
});
export const TransactionRecord = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Variant({ 'successful' : IDL.Null, 'failed' : IDL.Null }),
  'transactionType' : IDL.Variant({
    'creditFunding' : IDL.Null,
    'deposit' : IDL.Null,
  }),
  'source' : IDL.Text,
  'date' : IDL.Text,
  'amountCents' : IDL.Nat,
  'transactionId' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'customer' : IDL.Null,
  'seller' : IDL.Null,
  'employee' : IDL.Null,
  'marketer' : IDL.Null,
  'guest' : IDL.Null,
  'business' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'accountCreated' : IDL.Int,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'subscriptionId' : IDL.Opt(IDL.Text),
  'activeRole' : UserRole,
});
export const SellerOnboardingStep = IDL.Variant({
  'marketing' : IDL.Null,
  'termsAndConditions' : IDL.Null,
  'signup' : IDL.Null,
  'storeSetup' : IDL.Null,
  'websiteIntegration' : IDL.Null,
  'companyDetails' : IDL.Null,
});
export const SellerOnboardingProgress = IDL.Record({
  'isCompleted' : IDL.Bool,
  'lastUpdated' : IDL.Int,
  'timestamps' : IDL.Vec(IDL.Tuple(SellerOnboardingStep, IDL.Int)),
  'currentStep' : SellerOnboardingStep,
  'completedSteps' : IDL.Vec(SellerOnboardingStep),
});
export const RoleApplicationStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const RoleApplication = IDL.Record({
  'status' : RoleApplicationStatus,
  'applicant' : IDL.Principal,
  'requestedRole' : UserRole,
  'applicationDate' : IDL.Int,
  'reason' : IDL.Text,
});
export const TimeFrame = IDL.Variant({
  'today' : IDL.Null,
  'thisWeek' : IDL.Null,
  'allTime' : IDL.Null,
  'thisMonth' : IDL.Null,
});
export const SellerEarningsSummary = IDL.Record({
  'totalOrders' : IDL.Nat,
  'totalEarnings' : IDL.Nat,
  'totalShippingCosts' : IDL.Nat,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const UserRoleSummary = IDL.Record({
  'guestCount' : IDL.Nat,
  'adminCount' : IDL.Nat,
  'userCount' : IDL.Nat,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'approveRoleApplication' : IDL.Func([IDL.Principal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'assignRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'getAdminDashboardData' : IDL.Func([], [AdminDashboardData], ['query']),
  'getAdminFinancialState' : IDL.Func([], [AdminFinancialState], ['query']),
  'getAllTransactionHistory' : IDL.Func(
      [],
      [IDL.Vec(TransactionRecord)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getOnboarding' : IDL.Func(
      [],
      [IDL.Opt(SellerOnboardingProgress)],
      ['query'],
    ),
  'getOwnerEmail' : IDL.Func([], [IDL.Text], ['query']),
  'getPendingRoleApplications' : IDL.Func(
      [],
      [IDL.Vec(RoleApplication)],
      ['query'],
    ),
  'getSellerEarningsSummary' : IDL.Func(
      [TimeFrame],
      [SellerEarningsSummary],
      ['query'],
    ),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getTransactionRecordById' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(TransactionRecord)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserRoleSummary' : IDL.Func([], [UserRoleSummary], ['query']),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerOwnerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'rejectRoleApplication' : IDL.Func([IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveOnboarding' : IDL.Func([SellerOnboardingProgress], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'submitRoleApplication' : IDL.Func([UserRole, IDL.Text], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateAdminDashboardData' : IDL.Func([], [], []),
  'updateAdminFinancialState' : IDL.Func([AdminFinancialState], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const AdminPageSection = IDL.Variant({
    'b2b' : IDL.Null,
    'marketplace' : IDL.Null,
    'startups' : IDL.Null,
    'assistants' : IDL.Null,
    'businessDetails' : IDL.Null,
    'affiliate' : IDL.Null,
    'funding' : IDL.Null,
  });
  const AdminPageStatusDetails = IDL.Record({
    'version' : IDL.Text,
    'notes' : IDL.Text,
  });
  const AdminPageSectionStatus = IDL.Record({
    'status' : IDL.Variant({
      'completed' : IDL.Null,
      'comingSoon' : IDL.Null,
      'inProgress' : IDL.Null,
    }),
    'section' : AdminPageSection,
    'details' : IDL.Opt(AdminPageStatusDetails),
  });
  const MarketplaceRoadmap = IDL.Record({
    'progressPercentage' : IDL.Nat,
    'name' : IDL.Text,
    'completed' : IDL.Bool,
    'lastUpdated' : IDL.Int,
    'roadmapId' : IDL.Text,
    'notes' : IDL.Text,
  });
  const AdminDashboardData = IDL.Record({
    'adminSections' : IDL.Vec(AdminPageSectionStatus),
    'marketplaceRoadmap' : IDL.Vec(MarketplaceRoadmap),
  });
  const CreditAccount = IDL.Record({
    'creditLimitCents' : IDL.Nat,
    'usedAmountCents' : IDL.Nat,
  });
  const AdminFinancialState = IDL.Record({
    'creditAccount' : CreditAccount,
    'availableFundsCents' : IDL.Nat,
  });
  const TransactionRecord = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Variant({ 'successful' : IDL.Null, 'failed' : IDL.Null }),
    'transactionType' : IDL.Variant({
      'creditFunding' : IDL.Null,
      'deposit' : IDL.Null,
    }),
    'source' : IDL.Text,
    'date' : IDL.Text,
    'amountCents' : IDL.Nat,
    'transactionId' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'customer' : IDL.Null,
    'seller' : IDL.Null,
    'employee' : IDL.Null,
    'marketer' : IDL.Null,
    'guest' : IDL.Null,
    'business' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'accountCreated' : IDL.Int,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'subscriptionId' : IDL.Opt(IDL.Text),
    'activeRole' : UserRole,
  });
  const SellerOnboardingStep = IDL.Variant({
    'marketing' : IDL.Null,
    'termsAndConditions' : IDL.Null,
    'signup' : IDL.Null,
    'storeSetup' : IDL.Null,
    'websiteIntegration' : IDL.Null,
    'companyDetails' : IDL.Null,
  });
  const SellerOnboardingProgress = IDL.Record({
    'isCompleted' : IDL.Bool,
    'lastUpdated' : IDL.Int,
    'timestamps' : IDL.Vec(IDL.Tuple(SellerOnboardingStep, IDL.Int)),
    'currentStep' : SellerOnboardingStep,
    'completedSteps' : IDL.Vec(SellerOnboardingStep),
  });
  const RoleApplicationStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const RoleApplication = IDL.Record({
    'status' : RoleApplicationStatus,
    'applicant' : IDL.Principal,
    'requestedRole' : UserRole,
    'applicationDate' : IDL.Int,
    'reason' : IDL.Text,
  });
  const TimeFrame = IDL.Variant({
    'today' : IDL.Null,
    'thisWeek' : IDL.Null,
    'allTime' : IDL.Null,
    'thisMonth' : IDL.Null,
  });
  const SellerEarningsSummary = IDL.Record({
    'totalOrders' : IDL.Nat,
    'totalEarnings' : IDL.Nat,
    'totalShippingCosts' : IDL.Nat,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const UserRoleSummary = IDL.Record({
    'guestCount' : IDL.Nat,
    'adminCount' : IDL.Nat,
    'userCount' : IDL.Nat,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'approveRoleApplication' : IDL.Func([IDL.Principal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'assignRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'getAdminDashboardData' : IDL.Func([], [AdminDashboardData], ['query']),
    'getAdminFinancialState' : IDL.Func([], [AdminFinancialState], ['query']),
    'getAllTransactionHistory' : IDL.Func(
        [],
        [IDL.Vec(TransactionRecord)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getOnboarding' : IDL.Func(
        [],
        [IDL.Opt(SellerOnboardingProgress)],
        ['query'],
      ),
    'getOwnerEmail' : IDL.Func([], [IDL.Text], ['query']),
    'getPendingRoleApplications' : IDL.Func(
        [],
        [IDL.Vec(RoleApplication)],
        ['query'],
      ),
    'getSellerEarningsSummary' : IDL.Func(
        [TimeFrame],
        [SellerEarningsSummary],
        ['query'],
      ),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getTransactionRecordById' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(TransactionRecord)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserRoleSummary' : IDL.Func([], [UserRoleSummary], ['query']),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerOwnerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'rejectRoleApplication' : IDL.Func([IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveOnboarding' : IDL.Func([SellerOnboardingProgress], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'submitRoleApplication' : IDL.Func([UserRole, IDL.Text], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateAdminDashboardData' : IDL.Func([], [], []),
    'updateAdminFinancialState' : IDL.Func([AdminFinancialState], [], []),
  });
};

export const init = ({ IDL }) => { return []; };