/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Activity = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'isCompleted' : IDL.Bool,
  'description' : IDL.Text,
  'resourceLink' : IDL.Text,
});
export const AppIntegration = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'updatedAt' : IDL.Int,
  'apiCredentials' : IDL.Text,
  'category' : IDL.Text,
});
export const AppIntegrationRecord = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Variant({
    'active' : IDL.Null,
    'inactive' : IDL.Null,
    'error' : IDL.Null,
    'syncing' : IDL.Null,
  }),
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'updatedAt' : IDL.Int,
  'iconUrl' : IDL.Text,
  'webhookUrl' : IDL.Text,
});
export const B2BService = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'updatedAt' : IDL.Int,
  'category' : IDL.Text,
  'pricingModel' : IDL.Text,
});
export const DropshippingPartner = IDL.Record({
  'id' : IDL.Text,
  'healthMetrics' : IDL.Record({
    'failedSyncs' : IDL.Nat,
    'successfulSyncs' : IDL.Nat,
    'uptimePercent' : IDL.Float64,
    'lastSyncTime' : IDL.Opt(IDL.Int),
  }),
  'name' : IDL.Text,
  'apiKey' : IDL.Text,
  'apiUrl' : IDL.Text,
  'connectionStatus' : IDL.Variant({
    'disconnected' : IDL.Null,
    'connected' : IDL.Null,
  }),
});
export const Lesson = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'description' : IDL.Text,
  'videoLink' : IDL.Opt(IDL.Text),
});
export const Product = IDL.Record({
  'id' : IDL.Text,
  'inStock' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'image' : IDL.Opt(IDL.Text),
  'priceCents' : IDL.Nat,
});
export const VirtualMeeting = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'scheduledTime' : IDL.Int,
  'description' : IDL.Text,
  'meetingLink' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AccessRole = IDL.Variant({
  'b2bMember' : IDL.Null,
  'startUpMember' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'accountCreated' : IDL.Int,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'subscriptionId' : IDL.Opt(IDL.Text),
  'activeRole' : AccessRole,
});
export const ShoppingCart = IDL.Record({ 'products' : IDL.Vec(IDL.Text) });
export const FunnelPartner = IDL.Record({
  'partnerLink' : IDL.Text,
  'partnerName' : IDL.Text,
});
export const OrderStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const EcomOrder = IDL.Record({
  'status' : OrderStatus,
  'customerPrincipal' : IDL.Opt(IDL.Principal),
  'orderId' : IDL.Text,
  'totalAmount' : IDL.Nat,
  'products' : IDL.Vec(IDL.Text),
});
export const BusinessCreditData = IDL.Record({
  'completionPercentage' : IDL.Float64,
  'businessVerificationStatus' : IDL.Text,
  'creditBureauRegistrationStatus' : IDL.Text,
});
export const EducationalContent = IDL.Record({
  'virtualMeetings' : IDL.Vec(VirtualMeeting),
  'activities' : IDL.Vec(Activity),
  'lessons' : IDL.Vec(Lesson),
});
export const StartupProgramData = IDL.Record({
  'businessCredit' : BusinessCreditData,
  'educationalContent' : EducationalContent,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const UserWithRole = IDL.Record({
  'principal' : IDL.Principal,
  'profile' : UserProfile,
  'systemRole' : UserRole,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addActivity' : IDL.Func([Activity], [], []),
  'addAppIntegration' : IDL.Func([AppIntegration], [], []),
  'addAppIntegrationRecord' : IDL.Func([AppIntegrationRecord], [], []),
  'addB2BService' : IDL.Func([B2BService], [], []),
  'addDropshippingPartner' : IDL.Func([DropshippingPartner], [], []),
  'addLesson' : IDL.Func([Lesson], [], []),
  'addOrUpdateProduct' : IDL.Func([Product], [], []),
  'addToCart' : IDL.Func([IDL.Text], [], []),
  'addVirtualMeeting' : IDL.Func([VirtualMeeting], [], []),
  'addWebhookIntegrationRecord' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignUserAccessRole' : IDL.Func([IDL.Principal, AccessRole], [], []),
  'checkoutCart' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], []),
  'clearCart' : IDL.Func([], [], []),
  'completeActivity' : IDL.Func([IDL.Text], [], []),
  'completeLesson' : IDL.Func([IDL.Text], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'deleteActivity' : IDL.Func([IDL.Text], [], []),
  'deleteAppIntegration' : IDL.Func([IDL.Text], [], []),
  'deleteB2BService' : IDL.Func([IDL.Text], [], []),
  'deleteDropshippingPartner' : IDL.Func([IDL.Text], [], []),
  'deleteLesson' : IDL.Func([IDL.Text], [], []),
  'deleteProduct' : IDL.Func([IDL.Text], [], []),
  'deleteVirtualMeeting' : IDL.Func([IDL.Text], [], []),
  'getAdminDashboardStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'cartCount' : IDL.Nat,
          'pendingOrderCount' : IDL.Nat,
          'productCount' : IDL.Nat,
          'appIntegrationCount' : IDL.Nat,
          'orderCount' : IDL.Nat,
          'b2bServiceCount' : IDL.Nat,
          'dropshippingPartnerCount' : IDL.Nat,
          'completedOrderCount' : IDL.Nat,
          'userCount' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getAllAppIntegrations' : IDL.Func(
      [],
      [IDL.Vec(AppIntegrationRecord)],
      ['query'],
    ),
  'getAppIntegration' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(AppIntegration)],
      ['query'],
    ),
  'getAppIntegrationRecord' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(AppIntegrationRecord)],
      ['query'],
    ),
  'getB2BService' : IDL.Func([IDL.Text], [IDL.Opt(B2BService)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCart' : IDL.Func([], [IDL.Opt(ShoppingCart)], ['query']),
  'getDropshippingPartner' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(DropshippingPartner)],
      ['query'],
    ),
  'getMerchantFunnelPartner' : IDL.Func([], [FunnelPartner], ['query']),
  'getOrder' : IDL.Func([IDL.Text], [IDL.Opt(EcomOrder)], ['query']),
  'getPendingOrders' : IDL.Func([], [IDL.Vec(EcomOrder)], ['query']),
  'getProduct' : IDL.Func([IDL.Text], [IDL.Opt(Product)], ['query']),
  'getRoleSummary' : IDL.Func(
      [],
      [
        IDL.Record({
          'guestCount' : IDL.Nat,
          'startupMemberCount' : IDL.Nat,
          'b2bMemberCount' : IDL.Nat,
          'adminCount' : IDL.Nat,
          'userCount' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getServiceFee' : IDL.Func([IDL.Nat], [IDL.Nat], []),
  'getServiceFeePercentage' : IDL.Func([], [IDL.Float64], ['query']),
  'getStartupProgramData' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(StartupProgramData)],
      ['query'],
    ),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserOrders' : IDL.Func([], [IDL.Vec(EcomOrder)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isAuthenticated' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isOwner' : IDL.Func([], [IDL.Bool], ['query']),
  'isServiceFeeActive' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllOrders' : IDL.Func([], [IDL.Vec(EcomOrder)], ['query']),
  'listAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'listAllUsersWithRoles' : IDL.Func([], [IDL.Vec(UserWithRole)], ['query']),
  'listAppIntegrations' : IDL.Func([], [IDL.Vec(AppIntegration)], ['query']),
  'listB2BServices' : IDL.Func([], [IDL.Vec(B2BService)], ['query']),
  'listDropshippingPartners' : IDL.Func(
      [],
      [IDL.Vec(DropshippingPartner)],
      ['query'],
    ),
  'listProductsByName' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'listProductsByPrice' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'registerUserWithPaidPlan' : IDL.Func(
      [IDL.Text, IDL.Text, AccessRole, IDL.Text],
      [],
      [],
    ),
  'removeAppIntegrationRecord' : IDL.Func([IDL.Text], [], []),
  'removeFromCart' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveStartupProgramData' : IDL.Func([StartupProgramData], [], []),
  'setMerchantFunnelPartner' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'setOwnerPrincipal' : IDL.Func([], [], []),
  'setServiceFeePercentage' : IDL.Func([IDL.Float64], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'toggleAppIntegrationStatus' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'toggleB2BServiceStatus' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateActivity' : IDL.Func([Activity], [], []),
  'updateAppIntegration' : IDL.Func([AppIntegration], [], []),
  'updateAppIntegrationRecord' : IDL.Func([AppIntegrationRecord], [], []),
  'updateB2BService' : IDL.Func([B2BService], [], []),
  'updateBusinessVerificationStatus' : IDL.Func([IDL.Text], [], []),
  'updateCreditBureauRegistrationStatus' : IDL.Func([IDL.Text], [], []),
  'updateDropshippingPartner' : IDL.Func([DropshippingPartner], [], []),
  'updateDropshippingPartnerHealthMetrics' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Opt(IDL.Int), IDL.Float64],
      [],
      [],
    ),
  'updateLesson' : IDL.Func([Lesson], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Text, OrderStatus], [], []),
  'updateSubscriptionRole' : IDL.Func([IDL.Principal, AccessRole], [], []),
  'updateVirtualMeeting' : IDL.Func([VirtualMeeting], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Activity = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'isCompleted' : IDL.Bool,
    'description' : IDL.Text,
    'resourceLink' : IDL.Text,
  });
  const AppIntegration = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'updatedAt' : IDL.Int,
    'apiCredentials' : IDL.Text,
    'category' : IDL.Text,
  });
  const AppIntegrationRecord = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Variant({
      'active' : IDL.Null,
      'inactive' : IDL.Null,
      'error' : IDL.Null,
      'syncing' : IDL.Null,
    }),
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'updatedAt' : IDL.Int,
    'iconUrl' : IDL.Text,
    'webhookUrl' : IDL.Text,
  });
  const B2BService = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'updatedAt' : IDL.Int,
    'category' : IDL.Text,
    'pricingModel' : IDL.Text,
  });
  const DropshippingPartner = IDL.Record({
    'id' : IDL.Text,
    'healthMetrics' : IDL.Record({
      'failedSyncs' : IDL.Nat,
      'successfulSyncs' : IDL.Nat,
      'uptimePercent' : IDL.Float64,
      'lastSyncTime' : IDL.Opt(IDL.Int),
    }),
    'name' : IDL.Text,
    'apiKey' : IDL.Text,
    'apiUrl' : IDL.Text,
    'connectionStatus' : IDL.Variant({
      'disconnected' : IDL.Null,
      'connected' : IDL.Null,
    }),
  });
  const Lesson = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'description' : IDL.Text,
    'videoLink' : IDL.Opt(IDL.Text),
  });
  const Product = IDL.Record({
    'id' : IDL.Text,
    'inStock' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'image' : IDL.Opt(IDL.Text),
    'priceCents' : IDL.Nat,
  });
  const VirtualMeeting = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'scheduledTime' : IDL.Int,
    'description' : IDL.Text,
    'meetingLink' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AccessRole = IDL.Variant({
    'b2bMember' : IDL.Null,
    'startUpMember' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'accountCreated' : IDL.Int,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'subscriptionId' : IDL.Opt(IDL.Text),
    'activeRole' : AccessRole,
  });
  const ShoppingCart = IDL.Record({ 'products' : IDL.Vec(IDL.Text) });
  const FunnelPartner = IDL.Record({
    'partnerLink' : IDL.Text,
    'partnerName' : IDL.Text,
  });
  const OrderStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const EcomOrder = IDL.Record({
    'status' : OrderStatus,
    'customerPrincipal' : IDL.Opt(IDL.Principal),
    'orderId' : IDL.Text,
    'totalAmount' : IDL.Nat,
    'products' : IDL.Vec(IDL.Text),
  });
  const BusinessCreditData = IDL.Record({
    'completionPercentage' : IDL.Float64,
    'businessVerificationStatus' : IDL.Text,
    'creditBureauRegistrationStatus' : IDL.Text,
  });
  const EducationalContent = IDL.Record({
    'virtualMeetings' : IDL.Vec(VirtualMeeting),
    'activities' : IDL.Vec(Activity),
    'lessons' : IDL.Vec(Lesson),
  });
  const StartupProgramData = IDL.Record({
    'businessCredit' : BusinessCreditData,
    'educationalContent' : EducationalContent,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const UserWithRole = IDL.Record({
    'principal' : IDL.Principal,
    'profile' : UserProfile,
    'systemRole' : UserRole,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addActivity' : IDL.Func([Activity], [], []),
    'addAppIntegration' : IDL.Func([AppIntegration], [], []),
    'addAppIntegrationRecord' : IDL.Func([AppIntegrationRecord], [], []),
    'addB2BService' : IDL.Func([B2BService], [], []),
    'addDropshippingPartner' : IDL.Func([DropshippingPartner], [], []),
    'addLesson' : IDL.Func([Lesson], [], []),
    'addOrUpdateProduct' : IDL.Func([Product], [], []),
    'addToCart' : IDL.Func([IDL.Text], [], []),
    'addVirtualMeeting' : IDL.Func([VirtualMeeting], [], []),
    'addWebhookIntegrationRecord' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignUserAccessRole' : IDL.Func([IDL.Principal, AccessRole], [], []),
    'checkoutCart' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], []),
    'clearCart' : IDL.Func([], [], []),
    'completeActivity' : IDL.Func([IDL.Text], [], []),
    'completeLesson' : IDL.Func([IDL.Text], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'deleteActivity' : IDL.Func([IDL.Text], [], []),
    'deleteAppIntegration' : IDL.Func([IDL.Text], [], []),
    'deleteB2BService' : IDL.Func([IDL.Text], [], []),
    'deleteDropshippingPartner' : IDL.Func([IDL.Text], [], []),
    'deleteLesson' : IDL.Func([IDL.Text], [], []),
    'deleteProduct' : IDL.Func([IDL.Text], [], []),
    'deleteVirtualMeeting' : IDL.Func([IDL.Text], [], []),
    'getAdminDashboardStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'cartCount' : IDL.Nat,
            'pendingOrderCount' : IDL.Nat,
            'productCount' : IDL.Nat,
            'appIntegrationCount' : IDL.Nat,
            'orderCount' : IDL.Nat,
            'b2bServiceCount' : IDL.Nat,
            'dropshippingPartnerCount' : IDL.Nat,
            'completedOrderCount' : IDL.Nat,
            'userCount' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getAllAppIntegrations' : IDL.Func(
        [],
        [IDL.Vec(AppIntegrationRecord)],
        ['query'],
      ),
    'getAppIntegration' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(AppIntegration)],
        ['query'],
      ),
    'getAppIntegrationRecord' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(AppIntegrationRecord)],
        ['query'],
      ),
    'getB2BService' : IDL.Func([IDL.Text], [IDL.Opt(B2BService)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCart' : IDL.Func([], [IDL.Opt(ShoppingCart)], ['query']),
    'getDropshippingPartner' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(DropshippingPartner)],
        ['query'],
      ),
    'getMerchantFunnelPartner' : IDL.Func([], [FunnelPartner], ['query']),
    'getOrder' : IDL.Func([IDL.Text], [IDL.Opt(EcomOrder)], ['query']),
    'getPendingOrders' : IDL.Func([], [IDL.Vec(EcomOrder)], ['query']),
    'getProduct' : IDL.Func([IDL.Text], [IDL.Opt(Product)], ['query']),
    'getRoleSummary' : IDL.Func(
        [],
        [
          IDL.Record({
            'guestCount' : IDL.Nat,
            'startupMemberCount' : IDL.Nat,
            'b2bMemberCount' : IDL.Nat,
            'adminCount' : IDL.Nat,
            'userCount' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getServiceFee' : IDL.Func([IDL.Nat], [IDL.Nat], []),
    'getServiceFeePercentage' : IDL.Func([], [IDL.Float64], ['query']),
    'getStartupProgramData' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(StartupProgramData)],
        ['query'],
      ),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserOrders' : IDL.Func([], [IDL.Vec(EcomOrder)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isAuthenticated' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isOwner' : IDL.Func([], [IDL.Bool], ['query']),
    'isServiceFeeActive' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllOrders' : IDL.Func([], [IDL.Vec(EcomOrder)], ['query']),
    'listAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'listAllUsersWithRoles' : IDL.Func([], [IDL.Vec(UserWithRole)], ['query']),
    'listAppIntegrations' : IDL.Func([], [IDL.Vec(AppIntegration)], ['query']),
    'listB2BServices' : IDL.Func([], [IDL.Vec(B2BService)], ['query']),
    'listDropshippingPartners' : IDL.Func(
        [],
        [IDL.Vec(DropshippingPartner)],
        ['query'],
      ),
    'listProductsByName' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'listProductsByPrice' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'registerUserWithPaidPlan' : IDL.Func(
        [IDL.Text, IDL.Text, AccessRole, IDL.Text],
        [],
        [],
      ),
    'removeAppIntegrationRecord' : IDL.Func([IDL.Text], [], []),
    'removeFromCart' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveStartupProgramData' : IDL.Func([StartupProgramData], [], []),
    'setMerchantFunnelPartner' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'setOwnerPrincipal' : IDL.Func([], [], []),
    'setServiceFeePercentage' : IDL.Func([IDL.Float64], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'toggleAppIntegrationStatus' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'toggleB2BServiceStatus' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateActivity' : IDL.Func([Activity], [], []),
    'updateAppIntegration' : IDL.Func([AppIntegration], [], []),
    'updateAppIntegrationRecord' : IDL.Func([AppIntegrationRecord], [], []),
    'updateB2BService' : IDL.Func([B2BService], [], []),
    'updateBusinessVerificationStatus' : IDL.Func([IDL.Text], [], []),
    'updateCreditBureauRegistrationStatus' : IDL.Func([IDL.Text], [], []),
    'updateDropshippingPartner' : IDL.Func([DropshippingPartner], [], []),
    'updateDropshippingPartnerHealthMetrics' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Opt(IDL.Int), IDL.Float64],
        [],
        [],
      ),
    'updateLesson' : IDL.Func([Lesson], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Text, OrderStatus], [], []),
    'updateSubscriptionRole' : IDL.Func([IDL.Principal, AccessRole], [], []),
    'updateVirtualMeeting' : IDL.Func([VirtualMeeting], [], []),
  });
};

export const init = ({ IDL }) => { return []; };