/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AccessRole = { 'b2bMember' : null } |
  { 'startUpMember' : null } |
  { 'guest' : null };
export interface AccountAssignment {
  'sellerPrincipal' : Principal,
  'active' : boolean,
  'createdAt' : bigint,
  'accountNumber' : string,
}
export interface AdminDashboardData {
  'adminSections' : Array<AdminPageSectionStatus>,
  'marketplaceRoadmap' : Array<MarketplaceRoadmap>,
}
export interface AdminFinancialState {
  'creditAccount' : CreditAccount,
  'availableFundsCents' : bigint,
}
export type AdminPageSection = { 'b2b' : null } |
  { 'marketplace' : null } |
  { 'startups' : null } |
  { 'assistants' : null } |
  { 'businessDetails' : null } |
  { 'affiliate' : null } |
  { 'funding' : null };
export interface AdminPageSectionStatus {
  'status' : { 'completed' : null } |
    { 'comingSoon' : null } |
    { 'inProgress' : null },
  'section' : AdminPageSection,
  'details' : [] | [AdminPageStatusDetails],
}
export interface AdminPageStatusDetails { 'version' : string, 'notes' : string }
export interface AssistantKnowledgeEntry {
  'id' : string,
  'question' : string,
  'isBusinessOps' : boolean,
  'usageCount' : bigint,
  'lastUpdated' : bigint,
  'answer' : string,
  'isActive' : boolean,
  'category' : string,
}
export interface BusinessCreditCardApplication {
  'id' : string,
  'sellerPrincipal' : Principal,
  'submissionTimestamp' : bigint,
  'businessName' : string,
  'approvalTimestamp' : [] | [bigint],
  'applicationStatus' : CreditCardApplicationStatus,
  'rejectionTimestamp' : [] | [bigint],
  'reviewTimestamp' : [] | [bigint],
}
export interface BusinessDebitCardRequest {
  'id' : string,
  'sellerPrincipal' : Principal,
  'submissionTimestamp' : bigint,
  'businessName' : string,
  'approvalTimestamp' : [] | [bigint],
  'rejectionTimestamp' : [] | [bigint],
  'requestStatus' : DebitCardRequestStatus,
  'reviewTimestamp' : [] | [bigint],
}
export interface CreditAccount {
  'creditLimitCents' : bigint,
  'usedAmountCents' : bigint,
}
export type CreditCardApplicationStatus = { 'submitted' : null } |
  { 'approved' : null } |
  { 'rejected' : null } |
  { 'under_review' : null } |
  { 'draft' : null };
export type DebitCardRequestStatus = { 'submitted' : null } |
  { 'approved' : null } |
  { 'rejected' : null } |
  { 'under_review' : null } |
  { 'draft' : null };
export interface FunnelPartner {
  'partnerName' : string,
  'signupLink' : string,
  'profileLink' : string,
}
export interface MarketplaceRoadmap {
  'progressPercentage' : bigint,
  'name' : string,
  'completed' : boolean,
  'lastUpdated' : bigint,
  'roadmapId' : string,
  'notes' : string,
}
export type PayoutTransferStatus = { 'pending' : null } |
  { 'processed' : null } |
  { 'failed' : null };
export type PolicyIdentifier = { 'terms' : null } |
  { 'shipping' : null } |
  { 'privacy' : null } |
  { 'marketplaceWide' : null } |
  { 'returns' : null };
export interface PolicySignatureRecord {
  'signerName' : string,
  'signature' : string,
  'policyVersion' : string,
  'policyIdentifier' : PolicyIdentifier,
  'timestamp' : bigint,
}
export interface SellerPayoutProfile {
  'sellerPrincipal' : Principal,
  'createdAt' : bigint,
  'lastUpdated' : bigint,
  'designatedPayoutAccount' : string,
  'internalBalanceCents' : bigint,
}
export interface SellerPayoutTransferRecord {
  'id' : string,
  'status' : PayoutTransferStatus,
  'sellerPrincipal' : Principal,
  'createdAt' : bigint,
  'errorMessage' : [] | [string],
  'amountCents' : bigint,
  'processedAt' : [] | [bigint],
  'payoutAccount' : string,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UnansweredQuestion {
  'id' : string,
  'question' : string,
  'creationTime' : bigint,
  'interactionCount' : bigint,
  'categorySuggestion' : string,
}
export interface UserProfile {
  'accountCreated' : bigint,
  'fullName' : string,
  'email' : string,
  'subscriptionId' : [] | [string],
  'activeRole' : AccessRole,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserRoleSummary {
  'guestCount' : bigint,
  'adminCount' : bigint,
  'userCount' : bigint,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addKnowledgeEntry' : ActorMethod<[AssistantKnowledgeEntry], undefined>,
  'askAssistant' : ActorMethod<[string, string], [] | [string]>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createOrGetAccountNumber' : ActorMethod<[], AccountAssignment>,
  'createOrUpdatePayoutProfile' : ActorMethod<[string], SellerPayoutProfile>,
  'getAccountNumber' : ActorMethod<[], [] | [string]>,
  'getActiveKnowledgeByCategory' : ActorMethod<
    [string],
    Array<AssistantKnowledgeEntry>
  >,
  'getAdminDashboardData' : ActorMethod<[], AdminDashboardData>,
  'getAdminFinancialState' : ActorMethod<[], AdminFinancialState>,
  'getAssistantKnowledgeBase' : ActorMethod<[], Array<AssistantKnowledgeEntry>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFunnelPartner' : ActorMethod<[], FunnelPartner>,
  'getPayoutProfile' : ActorMethod<[], [] | [SellerPayoutProfile]>,
  'getSignatureByPolicy' : ActorMethod<
    [PolicyIdentifier],
    [] | [PolicySignatureRecord]
  >,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUnansweredQuestions' : ActorMethod<[], Array<UnansweredQuestion>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserRoleSummary' : ActorMethod<[], UserRoleSummary>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'recordCredit' : ActorMethod<[bigint], undefined>,
  'recordPayoutTransfer' : ActorMethod<
    [bigint, string],
    SellerPayoutTransferRecord
  >,
  'repayCredit' : ActorMethod<[bigint], undefined>,
  'requestBusinessDebitCard' : ActorMethod<[string], BusinessDebitCardRequest>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setOwnerPrincipal' : ActorMethod<[], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'signPolicy' : ActorMethod<[PolicySignatureRecord], undefined>,
  'submitBusinessCreditCardApplication' : ActorMethod<
    [string],
    BusinessCreditCardApplication
  >,
  'submitBusinessOpsQuestion' : ActorMethod<[string], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateAdminDashboardData' : ActorMethod<[], undefined>,
  'updateAvailableFunds' : ActorMethod<[bigint], undefined>,
  'updateCreditUsedAmount' : ActorMethod<[bigint], undefined>,
  'updateFunnelPartner' : ActorMethod<[FunnelPartner], undefined>,
  'updateKnowledgeEntry' : ActorMethod<[string, string], undefined>,
  'updateMarketplaceRoadmap' : ActorMethod<[], undefined>,
  'verifyPolicySignature' : ActorMethod<[PolicyIdentifier, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];