/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ShoppingCart {
    products: Array<string>;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface EducationalContent {
    virtualMeetings: Array<VirtualMeeting>;
    activities: Array<Activity>;
    lessons: Array<Lesson>;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface DropshippingPartner {
    id: string;
    healthMetrics: {
        failedSyncs: bigint;
        successfulSyncs: bigint;
        uptimePercent: number;
        lastSyncTime?: bigint;
    };
    name: string;
    apiKey: string;
    apiUrl: string;
    connectionStatus: Variant_disconnected_connected;
}
export interface B2BService {
    id: string;
    name: string;
    createdAt: bigint;
    description: string;
    isActive: boolean;
    updatedAt: bigint;
    category: string;
    pricingModel: string;
}
export interface Lesson {
    id: string;
    title: string;
    content: string;
    description: string;
    videoLink?: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface AppIntegration {
    id: string;
    name: string;
    createdAt: bigint;
    description: string;
    isActive: boolean;
    updatedAt: bigint;
    apiCredentials: string;
    category: string;
}
export interface AppIntegrationRecord {
    id: string;
    status: Variant_active_inactive_error_syncing;
    name: string;
    createdAt: bigint;
    description: string;
    updatedAt: bigint;
    iconUrl: string;
    webhookUrl: string;
}
export interface UserWithRole {
    principal: Principal;
    profile: UserProfile;
    systemRole: UserRole;
}
export interface EcomOrder {
    status: OrderStatus;
    customerPrincipal?: Principal;
    orderId: string;
    totalAmount: bigint;
    products: Array<string>;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface Activity {
    id: string;
    title: string;
    isCompleted: boolean;
    description: string;
    resourceLink: string;
}
export interface StartupProgramData {
    businessCredit: BusinessCreditData;
    educationalContent: EducationalContent;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface FunnelPartner {
    partnerLink: string;
    partnerName: string;
}
export interface BusinessCreditData {
    completionPercentage: number;
    businessVerificationStatus: string;
    creditBureauRegistrationStatus: string;
}
export interface VirtualMeeting {
    id: string;
    title: string;
    scheduledTime: bigint;
    description: string;
    meetingLink: string;
}
export interface Product {
    id: string;
    inStock: bigint;
    name: string;
    description: string;
    image?: string;
    priceCents: bigint;
}
export interface UserProfile {
    accountCreated: bigint;
    fullName: string;
    email: string;
    subscriptionId?: string;
    activeRole: AccessRole;
}
export enum AccessRole {
    b2bMember = "b2bMember",
    startUpMember = "startUpMember",
    guest = "guest"
}
export enum OrderStatus {
    cancelled = "cancelled",
    pending = "pending",
    completed = "completed",
    inProgress = "inProgress"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_active_inactive_error_syncing {
    active = "active",
    inactive = "inactive",
    error = "error",
    syncing = "syncing"
}
export enum Variant_disconnected_connected {
    disconnected = "disconnected",
    connected = "connected"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    addActivity(activity: Activity): Promise<void>;
    addAppIntegration(integration: AppIntegration): Promise<void>;
    addAppIntegrationRecord(record: AppIntegrationRecord): Promise<void>;
    addB2BService(service: B2BService): Promise<void>;
    addDropshippingPartner(partner: DropshippingPartner): Promise<void>;
    addLesson(lesson: Lesson): Promise<void>;
    addOrUpdateProduct(product: Product): Promise<void>;
    addToCart(productId: string): Promise<void>;
    addVirtualMeeting(meeting: VirtualMeeting): Promise<void>;
    addWebhookIntegrationRecord(webhookUrl: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignUserAccessRole(userPrincipal: Principal, newRole: AccessRole): Promise<void>;
    checkoutCart(_stripeSessionId: string): Promise<string | null>;
    clearCart(): Promise<void>;
    completeActivity(activityId: string): Promise<void>;
    completeLesson(lessonId: string): Promise<void>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    deleteActivity(activityId: string): Promise<void>;
    deleteAppIntegration(integrationId: string): Promise<void>;
    deleteB2BService(serviceId: string): Promise<void>;
    deleteDropshippingPartner(partnerId: string): Promise<void>;
    deleteLesson(lessonId: string): Promise<void>;
    deleteProduct(productId: string): Promise<void>;
    deleteVirtualMeeting(meetingId: string): Promise<void>;
    getAdminDashboardStats(): Promise<{
        cartCount: bigint;
        pendingOrderCount: bigint;
        productCount: bigint;
        appIntegrationCount: bigint;
        orderCount: bigint;
        b2bServiceCount: bigint;
        dropshippingPartnerCount: bigint;
        completedOrderCount: bigint;
        userCount: bigint;
    }>;
    getAllAppIntegrations(): Promise<Array<AppIntegrationRecord>>;
    getAppIntegration(integrationId: string): Promise<AppIntegration | null>;
    getAppIntegrationRecord(id: string): Promise<AppIntegrationRecord | null>;
    getB2BService(serviceId: string): Promise<B2BService | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCart(): Promise<ShoppingCart | null>;
    getDropshippingPartner(partnerId: string): Promise<DropshippingPartner | null>;
    getMerchantFunnelPartner(): Promise<FunnelPartner>;
    getOrder(orderId: string): Promise<EcomOrder | null>;
    getPendingOrders(): Promise<Array<EcomOrder>>;
    getProduct(productId: string): Promise<Product | null>;
    getRoleSummary(): Promise<{
        guestCount: bigint;
        startupMemberCount: bigint;
        b2bMemberCount: bigint;
        adminCount: bigint;
        userCount: bigint;
    }>;
    getServiceFee(priceCents: bigint): Promise<bigint>;
    getServiceFeePercentage(): Promise<number>;
    getStartupProgramData(userPrincipal: Principal): Promise<StartupProgramData | null>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getUserOrders(): Promise<Array<EcomOrder>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    initializeAccessControl(): Promise<void>;
    isAuthenticated(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    isOwner(): Promise<boolean>;
    isServiceFeeActive(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    listAllOrders(): Promise<Array<EcomOrder>>;
    listAllUsers(): Promise<Array<UserProfile>>;
    listAllUsersWithRoles(): Promise<Array<UserWithRole>>;
    listAppIntegrations(): Promise<Array<AppIntegration>>;
    listB2BServices(): Promise<Array<B2BService>>;
    listDropshippingPartners(): Promise<Array<DropshippingPartner>>;
    listProductsByName(): Promise<Array<Product>>;
    listProductsByPrice(): Promise<Array<Product>>;
    registerUserWithPaidPlan(email: string, fullName: string, role: AccessRole, _stripeSessionId: string): Promise<void>;
    removeAppIntegrationRecord(id: string): Promise<void>;
    removeFromCart(productId: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveStartupProgramData(startupData: StartupProgramData): Promise<void>;
    setMerchantFunnelPartner(partnerName: string, partnerLink: string): Promise<void>;
    setOwnerPrincipal(): Promise<void>;
    setServiceFeePercentage(percentage: number): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    toggleAppIntegrationStatus(integrationId: string, isActive: boolean): Promise<void>;
    toggleB2BServiceStatus(serviceId: string, isActive: boolean): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateActivity(activity: Activity): Promise<void>;
    updateAppIntegration(integration: AppIntegration): Promise<void>;
    updateAppIntegrationRecord(record: AppIntegrationRecord): Promise<void>;
    updateB2BService(service: B2BService): Promise<void>;
    updateBusinessVerificationStatus(status: string): Promise<void>;
    updateCreditBureauRegistrationStatus(status: string): Promise<void>;
    updateDropshippingPartner(partner: DropshippingPartner): Promise<void>;
    updateDropshippingPartnerHealthMetrics(partnerId: string, successfulSyncs: bigint, failedSyncs: bigint, lastSyncTime: bigint | null, uptimePercent: number): Promise<void>;
    updateLesson(lesson: Lesson): Promise<void>;
    updateOrderStatus(orderId: string, status: OrderStatus): Promise<void>;
    updateSubscriptionRole(userPrincipal: Principal, newRole: AccessRole): Promise<void>;
    updateVirtualMeeting(meeting: VirtualMeeting): Promise<void>;
}
import type { AccessRole as _AccessRole, Activity as _Activity, AppIntegration as _AppIntegration, AppIntegrationRecord as _AppIntegrationRecord, B2BService as _B2BService, BusinessCreditData as _BusinessCreditData, DropshippingPartner as _DropshippingPartner, EcomOrder as _EcomOrder, EducationalContent as _EducationalContent, Lesson as _Lesson, OrderStatus as _OrderStatus, Product as _Product, ShoppingCart as _ShoppingCart, StartupProgramData as _StartupProgramData, StripeSessionStatus as _StripeSessionStatus, UserProfile as _UserProfile, UserRole as _UserRole, UserWithRole as _UserWithRole, VirtualMeeting as _VirtualMeeting, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async addActivity(arg0: Activity): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addActivity(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addActivity(arg0);
            return result;
        }
    }
    async addAppIntegration(arg0: AppIntegration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAppIntegration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAppIntegration(arg0);
            return result;
        }
    }
    async addAppIntegrationRecord(arg0: AppIntegrationRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAppIntegrationRecord(to_candid_AppIntegrationRecord_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAppIntegrationRecord(to_candid_AppIntegrationRecord_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addB2BService(arg0: B2BService): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addB2BService(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addB2BService(arg0);
            return result;
        }
    }
    async addDropshippingPartner(arg0: DropshippingPartner): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addDropshippingPartner(to_candid_DropshippingPartner_n11(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDropshippingPartner(to_candid_DropshippingPartner_n11(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addLesson(arg0: Lesson): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addLesson(to_candid_Lesson_n15(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addLesson(to_candid_Lesson_n15(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addOrUpdateProduct(arg0: Product): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addOrUpdateProduct(to_candid_Product_n17(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOrUpdateProduct(to_candid_Product_n17(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addToCart(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addToCart(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addToCart(arg0);
            return result;
        }
    }
    async addVirtualMeeting(arg0: VirtualMeeting): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addVirtualMeeting(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addVirtualMeeting(arg0);
            return result;
        }
    }
    async addWebhookIntegrationRecord(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addWebhookIntegrationRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addWebhookIntegrationRecord(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n19(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n19(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignUserAccessRole(arg0: Principal, arg1: AccessRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignUserAccessRole(arg0, to_candid_AccessRole_n21(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignUserAccessRole(arg0, to_candid_AccessRole_n21(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async checkoutCart(arg0: string): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.checkoutCart(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkoutCart(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async clearCart(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearCart();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearCart();
            return result;
        }
    }
    async completeActivity(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.completeActivity(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeActivity(arg0);
            return result;
        }
    }
    async completeLesson(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.completeLesson(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeLesson(arg0);
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteActivity(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteActivity(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteActivity(arg0);
            return result;
        }
    }
    async deleteAppIntegration(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAppIntegration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAppIntegration(arg0);
            return result;
        }
    }
    async deleteB2BService(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteB2BService(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteB2BService(arg0);
            return result;
        }
    }
    async deleteDropshippingPartner(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDropshippingPartner(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDropshippingPartner(arg0);
            return result;
        }
    }
    async deleteLesson(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLesson(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLesson(arg0);
            return result;
        }
    }
    async deleteProduct(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return result;
        }
    }
    async deleteVirtualMeeting(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteVirtualMeeting(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteVirtualMeeting(arg0);
            return result;
        }
    }
    async getAdminDashboardStats(): Promise<{
        cartCount: bigint;
        pendingOrderCount: bigint;
        productCount: bigint;
        appIntegrationCount: bigint;
        orderCount: bigint;
        b2bServiceCount: bigint;
        dropshippingPartnerCount: bigint;
        completedOrderCount: bigint;
        userCount: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminDashboardStats();
            return result;
        }
    }
    async getAllAppIntegrations(): Promise<Array<AppIntegrationRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAppIntegrations();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAppIntegrations();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAppIntegration(arg0: string): Promise<AppIntegration | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppIntegration(arg0);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppIntegration(arg0);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAppIntegrationRecord(arg0: string): Promise<AppIntegrationRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppIntegrationRecord(arg0);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppIntegrationRecord(arg0);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getB2BService(arg0: string): Promise<B2BService | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getB2BService(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getB2BService(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCart(): Promise<ShoppingCart | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCart();
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCart();
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDropshippingPartner(arg0: string): Promise<DropshippingPartner | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDropshippingPartner(arg0);
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDropshippingPartner(arg0);
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMerchantFunnelPartner(): Promise<FunnelPartner> {
        if (this.processError) {
            try {
                const result = await this.actor.getMerchantFunnelPartner();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMerchantFunnelPartner();
            return result;
        }
    }
    async getOrder(arg0: string): Promise<EcomOrder | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrder(arg0);
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrder(arg0);
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingOrders(): Promise<Array<EcomOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingOrders();
                return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingOrders();
            return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProduct(arg0: string): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRoleSummary(): Promise<{
        guestCount: bigint;
        startupMemberCount: bigint;
        b2bMemberCount: bigint;
        adminCount: bigint;
        userCount: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getRoleSummary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRoleSummary();
            return result;
        }
    }
    async getServiceFee(arg0: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getServiceFee(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getServiceFee(arg0);
            return result;
        }
    }
    async getServiceFeePercentage(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getServiceFeePercentage();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getServiceFeePercentage();
            return result;
        }
    }
    async getStartupProgramData(arg0: Principal): Promise<StartupProgramData | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStartupProgramData(arg0);
                return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStartupProgramData(arg0);
            return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n63(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n63(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserOrders(): Promise<Array<EcomOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserOrders();
                return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserOrders();
            return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isAuthenticated(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAuthenticated();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAuthenticated();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isOwner(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isOwner();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isOwner();
            return result;
        }
    }
    async isServiceFeeActive(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isServiceFeeActive();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isServiceFeeActive();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async listAllOrders(): Promise<Array<EcomOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllOrders();
                return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllOrders();
            return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAllUsers(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllUsers();
                return from_candid_vec_n66(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllUsers();
            return from_candid_vec_n66(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAllUsersWithRoles(): Promise<Array<UserWithRole>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllUsersWithRoles();
                return from_candid_vec_n67(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllUsersWithRoles();
            return from_candid_vec_n67(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAppIntegrations(): Promise<Array<AppIntegration>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAppIntegrations();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAppIntegrations();
            return result;
        }
    }
    async listB2BServices(): Promise<Array<B2BService>> {
        if (this.processError) {
            try {
                const result = await this.actor.listB2BServices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listB2BServices();
            return result;
        }
    }
    async listDropshippingPartners(): Promise<Array<DropshippingPartner>> {
        if (this.processError) {
            try {
                const result = await this.actor.listDropshippingPartners();
                return from_candid_vec_n70(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listDropshippingPartners();
            return from_candid_vec_n70(this._uploadFile, this._downloadFile, result);
        }
    }
    async listProductsByName(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProductsByName();
                return from_candid_vec_n71(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProductsByName();
            return from_candid_vec_n71(this._uploadFile, this._downloadFile, result);
        }
    }
    async listProductsByPrice(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProductsByPrice();
                return from_candid_vec_n71(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProductsByPrice();
            return from_candid_vec_n71(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerUserWithPaidPlan(arg0: string, arg1: string, arg2: AccessRole, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUserWithPaidPlan(arg0, arg1, to_candid_AccessRole_n21(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUserWithPaidPlan(arg0, arg1, to_candid_AccessRole_n21(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async removeAppIntegrationRecord(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeAppIntegrationRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeAppIntegrationRecord(arg0);
            return result;
        }
    }
    async removeFromCart(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFromCart(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFromCart(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n72(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n72(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveStartupProgramData(arg0: StartupProgramData): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveStartupProgramData(to_candid_StartupProgramData_n74(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveStartupProgramData(to_candid_StartupProgramData_n74(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setMerchantFunnelPartner(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setMerchantFunnelPartner(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setMerchantFunnelPartner(arg0, arg1);
            return result;
        }
    }
    async setOwnerPrincipal(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setOwnerPrincipal();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setOwnerPrincipal();
            return result;
        }
    }
    async setServiceFeePercentage(arg0: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setServiceFeePercentage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setServiceFeePercentage(arg0);
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async toggleAppIntegrationStatus(arg0: string, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleAppIntegrationStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleAppIntegrationStatus(arg0, arg1);
            return result;
        }
    }
    async toggleB2BServiceStatus(arg0: string, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleB2BServiceStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleB2BServiceStatus(arg0, arg1);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateActivity(arg0: Activity): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateActivity(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateActivity(arg0);
            return result;
        }
    }
    async updateAppIntegration(arg0: AppIntegration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAppIntegration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAppIntegration(arg0);
            return result;
        }
    }
    async updateAppIntegrationRecord(arg0: AppIntegrationRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAppIntegrationRecord(to_candid_AppIntegrationRecord_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAppIntegrationRecord(to_candid_AppIntegrationRecord_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateB2BService(arg0: B2BService): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateB2BService(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateB2BService(arg0);
            return result;
        }
    }
    async updateBusinessVerificationStatus(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBusinessVerificationStatus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBusinessVerificationStatus(arg0);
            return result;
        }
    }
    async updateCreditBureauRegistrationStatus(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCreditBureauRegistrationStatus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCreditBureauRegistrationStatus(arg0);
            return result;
        }
    }
    async updateDropshippingPartner(arg0: DropshippingPartner): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDropshippingPartner(to_candid_DropshippingPartner_n11(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDropshippingPartner(to_candid_DropshippingPartner_n11(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateDropshippingPartnerHealthMetrics(arg0: string, arg1: bigint, arg2: bigint, arg3: bigint | null, arg4: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDropshippingPartnerHealthMetrics(arg0, arg1, arg2, to_candid_opt_n79(this._uploadFile, this._downloadFile, arg3), arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDropshippingPartnerHealthMetrics(arg0, arg1, arg2, to_candid_opt_n79(this._uploadFile, this._downloadFile, arg3), arg4);
            return result;
        }
    }
    async updateLesson(arg0: Lesson): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLesson(to_candid_Lesson_n15(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLesson(to_candid_Lesson_n15(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateOrderStatus(arg0: string, arg1: OrderStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n80(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n80(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateSubscriptionRole(arg0: Principal, arg1: AccessRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSubscriptionRole(arg0, to_candid_AccessRole_n21(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSubscriptionRole(arg0, to_candid_AccessRole_n21(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateVirtualMeeting(arg0: VirtualMeeting): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVirtualMeeting(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVirtualMeeting(arg0);
            return result;
        }
    }
}
function from_candid_AccessRole_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AccessRole): AccessRole {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_AppIntegrationRecord_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppIntegrationRecord): AppIntegrationRecord {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_DropshippingPartner_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DropshippingPartner): DropshippingPartner {
    return from_candid_record_n41(_uploadFile, _downloadFile, value);
}
function from_candid_EcomOrder_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EcomOrder): EcomOrder {
    return from_candid_record_n47(_uploadFile, _downloadFile, value);
}
function from_candid_EducationalContent_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EducationalContent): EducationalContent {
    return from_candid_record_n59(_uploadFile, _downloadFile, value);
}
function from_candid_Lesson_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Lesson): Lesson {
    return from_candid_record_n62(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n49(_uploadFile, _downloadFile, value);
}
function from_candid_Product_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Product {
    return from_candid_record_n54(_uploadFile, _downloadFile, value);
}
function from_candid_StartupProgramData_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StartupProgramData): StartupProgramData {
    return from_candid_record_n57(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n64(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_UserWithRole_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserWithRole): UserWithRole {
    return from_candid_record_n69(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AppIntegration]): AppIntegration | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AppIntegrationRecord]): AppIntegrationRecord | null {
    return value.length === 0 ? null : from_candid_AppIntegrationRecord_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_B2BService]): B2BService | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n32(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ShoppingCart]): ShoppingCart | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DropshippingPartner]): DropshippingPartner | null {
    return value.length === 0 ? null : from_candid_DropshippingPartner_n40(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_EcomOrder]): EcomOrder | null {
    return value.length === 0 ? null : from_candid_EcomOrder_n46(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Product]): Product | null {
    return value.length === 0 ? null : from_candid_Product_n53(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StartupProgramData]): StartupProgramData | null {
    return value.length === 0 ? null : from_candid_StartupProgramData_n56(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: {
        active: null;
    } | {
        inactive: null;
    } | {
        error: null;
    } | {
        syncing: null;
    };
    name: string;
    createdAt: bigint;
    description: string;
    updatedAt: bigint;
    iconUrl: string;
    webhookUrl: string;
}): {
    id: string;
    status: Variant_active_inactive_error_syncing;
    name: string;
    createdAt: bigint;
    description: string;
    updatedAt: bigint;
    iconUrl: string;
    webhookUrl: string;
} {
    return {
        id: value.id,
        status: from_candid_variant_n27(_uploadFile, _downloadFile, value.status),
        name: value.name,
        createdAt: value.createdAt,
        description: value.description,
        updatedAt: value.updatedAt,
        iconUrl: value.iconUrl,
        webhookUrl: value.webhookUrl
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    accountCreated: bigint;
    fullName: string;
    email: string;
    subscriptionId: [] | [string];
    activeRole: _AccessRole;
}): {
    accountCreated: bigint;
    fullName: string;
    email: string;
    subscriptionId?: string;
    activeRole: AccessRole;
} {
    return {
        accountCreated: value.accountCreated,
        fullName: value.fullName,
        email: value.email,
        subscriptionId: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.subscriptionId)),
        activeRole: from_candid_AccessRole_n34(_uploadFile, _downloadFile, value.activeRole)
    };
}
function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    healthMetrics: {
        failedSyncs: bigint;
        successfulSyncs: bigint;
        uptimePercent: number;
        lastSyncTime: [] | [bigint];
    };
    name: string;
    apiKey: string;
    apiUrl: string;
    connectionStatus: {
        disconnected: null;
    } | {
        connected: null;
    };
}): {
    id: string;
    healthMetrics: {
        failedSyncs: bigint;
        successfulSyncs: bigint;
        uptimePercent: number;
        lastSyncTime?: bigint;
    };
    name: string;
    apiKey: string;
    apiUrl: string;
    connectionStatus: Variant_disconnected_connected;
} {
    return {
        id: value.id,
        healthMetrics: from_candid_record_n42(_uploadFile, _downloadFile, value.healthMetrics),
        name: value.name,
        apiKey: value.apiKey,
        apiUrl: value.apiUrl,
        connectionStatus: from_candid_variant_n44(_uploadFile, _downloadFile, value.connectionStatus)
    };
}
function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    failedSyncs: bigint;
    successfulSyncs: bigint;
    uptimePercent: number;
    lastSyncTime: [] | [bigint];
}): {
    failedSyncs: bigint;
    successfulSyncs: bigint;
    uptimePercent: number;
    lastSyncTime?: bigint;
} {
    return {
        failedSyncs: value.failedSyncs,
        successfulSyncs: value.successfulSyncs,
        uptimePercent: value.uptimePercent,
        lastSyncTime: record_opt_to_undefined(from_candid_opt_n43(_uploadFile, _downloadFile, value.lastSyncTime))
    };
}
function from_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _OrderStatus;
    customerPrincipal: [] | [Principal];
    orderId: string;
    totalAmount: bigint;
    products: Array<string>;
}): {
    status: OrderStatus;
    customerPrincipal?: Principal;
    orderId: string;
    totalAmount: bigint;
    products: Array<string>;
} {
    return {
        status: from_candid_OrderStatus_n48(_uploadFile, _downloadFile, value.status),
        customerPrincipal: record_opt_to_undefined(from_candid_opt_n50(_uploadFile, _downloadFile, value.customerPrincipal)),
        orderId: value.orderId,
        totalAmount: value.totalAmount,
        products: value.products
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    inStock: bigint;
    name: string;
    description: string;
    image: [] | [string];
    priceCents: bigint;
}): {
    id: string;
    inStock: bigint;
    name: string;
    description: string;
    image?: string;
    priceCents: bigint;
} {
    return {
        id: value.id,
        inStock: value.inStock,
        name: value.name,
        description: value.description,
        image: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.image)),
        priceCents: value.priceCents
    };
}
function from_candid_record_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    businessCredit: _BusinessCreditData;
    educationalContent: _EducationalContent;
}): {
    businessCredit: BusinessCreditData;
    educationalContent: EducationalContent;
} {
    return {
        businessCredit: value.businessCredit,
        educationalContent: from_candid_EducationalContent_n58(_uploadFile, _downloadFile, value.educationalContent)
    };
}
function from_candid_record_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    virtualMeetings: Array<_VirtualMeeting>;
    activities: Array<_Activity>;
    lessons: Array<_Lesson>;
}): {
    virtualMeetings: Array<VirtualMeeting>;
    activities: Array<Activity>;
    lessons: Array<Lesson>;
} {
    return {
        virtualMeetings: value.virtualMeetings,
        activities: value.activities,
        lessons: from_candid_vec_n60(_uploadFile, _downloadFile, value.lessons)
    };
}
function from_candid_record_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    content: string;
    description: string;
    videoLink: [] | [string];
}): {
    id: string;
    title: string;
    content: string;
    description: string;
    videoLink?: string;
} {
    return {
        id: value.id,
        title: value.title,
        content: value.content,
        description: value.description,
        videoLink: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.videoLink))
    };
}
function from_candid_record_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_record_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: Principal;
    profile: _UserProfile;
    systemRole: _UserRole;
}): {
    principal: Principal;
    profile: UserProfile;
    systemRole: UserRole;
} {
    return {
        principal: value.principal,
        profile: from_candid_UserProfile_n32(_uploadFile, _downloadFile, value.profile),
        systemRole: from_candid_UserRole_n36(_uploadFile, _downloadFile, value.systemRole)
    };
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    inactive: null;
} | {
    error: null;
} | {
    syncing: null;
}): Variant_active_inactive_error_syncing {
    return "active" in value ? Variant_active_inactive_error_syncing.active : "inactive" in value ? Variant_active_inactive_error_syncing.inactive : "error" in value ? Variant_active_inactive_error_syncing.error : "syncing" in value ? Variant_active_inactive_error_syncing.syncing : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    b2bMember: null;
} | {
    startUpMember: null;
} | {
    guest: null;
}): AccessRole {
    return "b2bMember" in value ? AccessRole.b2bMember : "startUpMember" in value ? AccessRole.startUpMember : "guest" in value ? AccessRole.guest : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    disconnected: null;
} | {
    connected: null;
}): Variant_disconnected_connected {
    return "disconnected" in value ? Variant_disconnected_connected.disconnected : "connected" in value ? Variant_disconnected_connected.connected : value;
}
function from_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    inProgress: null;
}): OrderStatus {
    return "cancelled" in value ? OrderStatus.cancelled : "pending" in value ? OrderStatus.pending : "completed" in value ? OrderStatus.completed : "inProgress" in value ? OrderStatus.inProgress : value;
}
function from_candid_variant_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n65(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AppIntegrationRecord>): Array<AppIntegrationRecord> {
    return value.map((x)=>from_candid_AppIntegrationRecord_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_EcomOrder>): Array<EcomOrder> {
    return value.map((x)=>from_candid_EcomOrder_n46(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Lesson>): Array<Lesson> {
    return value.map((x)=>from_candid_Lesson_n61(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Array<UserProfile> {
    return value.map((x)=>from_candid_UserProfile_n32(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserWithRole>): Array<UserWithRole> {
    return value.map((x)=>from_candid_UserWithRole_n68(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DropshippingPartner>): Array<DropshippingPartner> {
    return value.map((x)=>from_candid_DropshippingPartner_n40(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Array<Product> {
    return value.map((x)=>from_candid_Product_n53(_uploadFile, _downloadFile, x));
}
function to_candid_AccessRole_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AccessRole): _AccessRole {
    return to_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function to_candid_AppIntegrationRecord_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppIntegrationRecord): _AppIntegrationRecord {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_DropshippingPartner_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DropshippingPartner): _DropshippingPartner {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_EducationalContent_n76(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EducationalContent): _EducationalContent {
    return to_candid_record_n77(_uploadFile, _downloadFile, value);
}
function to_candid_Lesson_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Lesson): _Lesson {
    return to_candid_record_n16(_uploadFile, _downloadFile, value);
}
function to_candid_OrderStatus_n80(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n81(_uploadFile, _downloadFile, value);
}
function to_candid_Product_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Product): _Product {
    return to_candid_record_n18(_uploadFile, _downloadFile, value);
}
function to_candid_StartupProgramData_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StartupProgramData): _StartupProgramData {
    return to_candid_record_n75(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n73(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n79(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    healthMetrics: {
        failedSyncs: bigint;
        successfulSyncs: bigint;
        uptimePercent: number;
        lastSyncTime?: bigint;
    };
    name: string;
    apiKey: string;
    apiUrl: string;
    connectionStatus: Variant_disconnected_connected;
}): {
    id: string;
    healthMetrics: {
        failedSyncs: bigint;
        successfulSyncs: bigint;
        uptimePercent: number;
        lastSyncTime: [] | [bigint];
    };
    name: string;
    apiKey: string;
    apiUrl: string;
    connectionStatus: {
        disconnected: null;
    } | {
        connected: null;
    };
} {
    return {
        id: value.id,
        healthMetrics: to_candid_record_n13(_uploadFile, _downloadFile, value.healthMetrics),
        name: value.name,
        apiKey: value.apiKey,
        apiUrl: value.apiUrl,
        connectionStatus: to_candid_variant_n14(_uploadFile, _downloadFile, value.connectionStatus)
    };
}
function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    failedSyncs: bigint;
    successfulSyncs: bigint;
    uptimePercent: number;
    lastSyncTime?: bigint;
}): {
    failedSyncs: bigint;
    successfulSyncs: bigint;
    uptimePercent: number;
    lastSyncTime: [] | [bigint];
} {
    return {
        failedSyncs: value.failedSyncs,
        successfulSyncs: value.successfulSyncs,
        uptimePercent: value.uptimePercent,
        lastSyncTime: value.lastSyncTime ? candid_some(value.lastSyncTime) : candid_none()
    };
}
function to_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    content: string;
    description: string;
    videoLink?: string;
}): {
    id: string;
    title: string;
    content: string;
    description: string;
    videoLink: [] | [string];
} {
    return {
        id: value.id,
        title: value.title,
        content: value.content,
        description: value.description,
        videoLink: value.videoLink ? candid_some(value.videoLink) : candid_none()
    };
}
function to_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    inStock: bigint;
    name: string;
    description: string;
    image?: string;
    priceCents: bigint;
}): {
    id: string;
    inStock: bigint;
    name: string;
    description: string;
    image: [] | [string];
    priceCents: bigint;
} {
    return {
        id: value.id,
        inStock: value.inStock,
        name: value.name,
        description: value.description,
        image: value.image ? candid_some(value.image) : candid_none(),
        priceCents: value.priceCents
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    accountCreated: bigint;
    fullName: string;
    email: string;
    subscriptionId?: string;
    activeRole: AccessRole;
}): {
    accountCreated: bigint;
    fullName: string;
    email: string;
    subscriptionId: [] | [string];
    activeRole: _AccessRole;
} {
    return {
        accountCreated: value.accountCreated,
        fullName: value.fullName,
        email: value.email,
        subscriptionId: value.subscriptionId ? candid_some(value.subscriptionId) : candid_none(),
        activeRole: to_candid_AccessRole_n21(_uploadFile, _downloadFile, value.activeRole)
    };
}
function to_candid_record_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    businessCredit: BusinessCreditData;
    educationalContent: EducationalContent;
}): {
    businessCredit: _BusinessCreditData;
    educationalContent: _EducationalContent;
} {
    return {
        businessCredit: value.businessCredit,
        educationalContent: to_candid_EducationalContent_n76(_uploadFile, _downloadFile, value.educationalContent)
    };
}
function to_candid_record_n77(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    virtualMeetings: Array<VirtualMeeting>;
    activities: Array<Activity>;
    lessons: Array<Lesson>;
}): {
    virtualMeetings: Array<_VirtualMeeting>;
    activities: Array<_Activity>;
    lessons: Array<_Lesson>;
} {
    return {
        virtualMeetings: value.virtualMeetings,
        activities: value.activities,
        lessons: to_candid_vec_n78(_uploadFile, _downloadFile, value.lessons)
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: Variant_active_inactive_error_syncing;
    name: string;
    createdAt: bigint;
    description: string;
    updatedAt: bigint;
    iconUrl: string;
    webhookUrl: string;
}): {
    id: string;
    status: {
        active: null;
    } | {
        inactive: null;
    } | {
        error: null;
    } | {
        syncing: null;
    };
    name: string;
    createdAt: bigint;
    description: string;
    updatedAt: bigint;
    iconUrl: string;
    webhookUrl: string;
} {
    return {
        id: value.id,
        status: to_candid_variant_n10(_uploadFile, _downloadFile, value.status),
        name: value.name,
        createdAt: value.createdAt,
        description: value.description,
        updatedAt: value.updatedAt,
        iconUrl: value.iconUrl,
        webhookUrl: value.webhookUrl
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_active_inactive_error_syncing): {
    active: null;
} | {
    inactive: null;
} | {
    error: null;
} | {
    syncing: null;
} {
    return value == Variant_active_inactive_error_syncing.active ? {
        active: null
    } : value == Variant_active_inactive_error_syncing.inactive ? {
        inactive: null
    } : value == Variant_active_inactive_error_syncing.error ? {
        error: null
    } : value == Variant_active_inactive_error_syncing.syncing ? {
        syncing: null
    } : value;
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_disconnected_connected): {
    disconnected: null;
} | {
    connected: null;
} {
    return value == Variant_disconnected_connected.disconnected ? {
        disconnected: null
    } : value == Variant_disconnected_connected.connected ? {
        connected: null
    } : value;
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AccessRole): {
    b2bMember: null;
} | {
    startUpMember: null;
} | {
    guest: null;
} {
    return value == AccessRole.b2bMember ? {
        b2bMember: null
    } : value == AccessRole.startUpMember ? {
        startUpMember: null
    } : value == AccessRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n81(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    inProgress: null;
} {
    return value == OrderStatus.cancelled ? {
        cancelled: null
    } : value == OrderStatus.pending ? {
        pending: null
    } : value == OrderStatus.completed ? {
        completed: null
    } : value == OrderStatus.inProgress ? {
        inProgress: null
    } : value;
}
function to_candid_vec_n78(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Lesson>): Array<_Lesson> {
    return value.map((x)=>to_candid_Lesson_n15(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
